name: ccy-helper

on:
  schedule:
    - cron: "20 21 * * *" # 该时间为UTC时间，比北京时间晚8个小时，每天早上7点自动执行（需要注意该时间不准时，会有不同程度的分钟数的延迟）

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Run Project
        run: npm install && npm run server # 安装依赖并执行server
